# Site settings
author: Mario Terrazas
title: Software Engineering the New Challenge 
header-img: img/home-bg.png
email: mtrrzs@hotmail.com
copyright_name: Mario Terrazas
description: > # this means to ignore newlines until "baseurl:"
  From Finance to Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mtrrzs

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
